name = "ipfs"
compatibility_date = "2025-01-01"

# Cloudflare Pages 的静态构建产物目录（Vite 默认是 dist）
pages_build_output_dir = "dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "ipfs"
database_id = "b855d5a7-ef76-4fcd-be54-3fab4fe285e3"
